package com.example.v112.agent;

import com.example.v112.llm.LlmGateway;
import com.example.v112.llm.LlmResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class AgentLoopService {
    private final LlmGateway llm;
    private final ToolDispatcher tools;
    private final int maxIterations;

    public AgentLoopService(LlmGateway llm, ToolDispatcher tools, @Value("${agent.max-iterations:4}") int maxIterations) {
        this.llm = llm;
        this.tools = tools;
        this.maxIterations = maxIterations;
    }

    public AgentResult run(String input) {
        List<String> trace = new ArrayList<>();
        trace.add("PLAN: agent loop started");
        var context = tools.execute("searchKnowledge", input);
        trace.add("TOOL searchKnowledge: " + context.observation());
        var skill = tools.execute("loadSkill", "cobol-migration");
        trace.add("TOOL loadSkill: " + skill.success());
        LlmResponse response = llm.generate(
                "You are an enterprise migration analysis agent. Use context and skill instructions and provide next steps.",
                "User request: " + input + "\nContext: " + context.observation() + "\nSkill: " + skill.observation() + "\nMax iterations configured: " + maxIterations
        );
        trace.add("FINAL: generated by " + response.provider());
        return new AgentResult(response, trace);
    }

    public record AgentResult(LlmResponse response, List<String> trace) {
    }
}
